Controllers/StockInController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.IO;
using System.Linq;
using System.Text;
using System.Reflection;
using System.ComponentModel;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using OfficeOpenXml;
using OfficeOpenXml.Style; 
using OfficeOpenXml.Table;
using PTum.Data;
using PTum.Models;
using Microsoft.AspNetCore.Http;

namespace Ptum.Controllers
{
    public class StockInController : Controller
    {
        private readonly PTumContext _context;

        public StockInController(PTumContext context)
        {
            _context = context;
        }

        // GET: StockIn
        public async Task<IActionResult> Index()
        {
            if(IsNotLogin()){
                return Unauthorized();
            }
            return View(await _context.Tb_stock_in.ToListAsync());
        }

        public async Task<IActionResult> Excel()
        {

            var time = DateTime.Now.ToString("yyyyMMddHHmmss");
            var fileName = $"StockIN_{time}.xlsx";
            var filepath = $"wwwroot/excel/stockin/{fileName}";
            var originalFileName = $"Template_StockIN.xlsx";
            var originalFilePath = $"wwwroot/excel/_master/{originalFileName}";

            var tb_mst_product = await _context.Tb_mst_product.ToListAsync();

            using(var package = new ExcelPackage(new FileInfo(originalFilePath)))
            {
                ExcelWorksheet worksheet = package.Workbook.Worksheets[0];
        
                int recordIndex = 3; 
                
                foreach (var item in tb_mst_product) 
                { 
                    worksheet.Cells[recordIndex, 1].Value = item.Id; 
                    worksheet.Cells[recordIndex, 2].Value = (recordIndex-2).ToString(); 
                    worksheet.Cells[recordIndex, 3].Value = item.prd_category;
                    worksheet.Cells[recordIndex, 4].Value = item.prd_code; 
                    worksheet.Cells[recordIndex, 5].Value = item.prd_type; 
                    worksheet.Cells[recordIndex, 6].Value = item.prd_model; 
                    worksheet.Cells[recordIndex, 7].Value = item.prd_cpt_name; 
                    worksheet.Cells[recordIndex, 8].Value = item.prd_fixasset_name; 
                    worksheet.Cells[recordIndex, 9].Value = item.prd_serial_num; 
                    recordIndex++; 
                } 
                package.SaveAs(new FileInfo(filepath));
                package.Dispose();
            }  

            byte[] fileBytes = System.IO.File.ReadAllBytes(filepath);
            return File(fileBytes, "application/x-msdownload", fileName); 

        }

        // GET: StockIn/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tb_stock_in = await _context.Tb_stock_in
                .FirstOrDefaultAsync(m => m.id_in == id);
            if (tb_stock_in == null)
            {
                return NotFound();
            }

            return View(tb_stock_in);
        }

        // GET: StockIn/Create
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Tb_stock_in tb_stock_in)
        {
            if (ModelState.IsValid)
            {
                _context.Add(new Tb_stock_in
                {
                    prd_code = tb_stock_in.prd_code,
                    prd_inqty = tb_stock_in.prd_inqty,
                    in_datetime = DateTime.Now,
                    in_name = HttpContext.Session.GetString("_Name")?? "000000",
                });
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View();
        }

        // POST: StockIn/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateExcel([Bind("id_in,prd_code,prd_inqty,in_status,in_datetime,in_name,in_last_uptime,in_last_upname")] Tb_stock_in tb_stock_in, List<IFormFile> files)
        {
            var time = DateTime.Now.ToString("yyyyMMddHHmmss");
            long size = files.Sum(f => f.Length);
            string filePath = null;

            foreach (var formFile in files)
            {
                if (formFile.Length > 0)
                {
                    filePath = Path.Combine("./wwwroot/excel/stockin/", $"StockIn_{time}.xlsx");
                    Console.WriteLine(filePath);
                    using (var stream = System.IO.File.Create(filePath))
                    {
                        await formFile.CopyToAsync(stream);
                    }
                }
            }

            if(System.IO.File.Exists(filePath)){
                Console.WriteLine("File exists.");
                using(var package = new ExcelPackage(new FileInfo(filePath)))
                {
                    ExcelWorksheet worksheet = package.Workbook.Worksheets[0];
                    int rowCount = worksheet.Dimension.Rows;
                    int colCount = worksheet.Dimension.Columns;
                    for (int row = 3; row <= rowCount; row++){
                        if(worksheet.Cells[row, 4].Value!=null && worksheet.Cells[row, 10].Value!=null){
                            _context.Add(new Tb_stock_in
                            {
                                prd_code = worksheet.Cells[row, 4].Value.ToString().Trim(),
                                prd_inqty = int.Parse(worksheet.Cells[row, 10].Value.ToString().Trim()),
                                in_datetime = DateTime.Now,
                                in_name = HttpContext.Session.GetString("_Name"),
                            });
                            await _context.SaveChangesAsync();
                        }
                    }
                }
            }


            return Ok(new { success= true, count = files.Count, size });
        }

        // GET: StockIn/Edit/5
        // public async Task<IActionResult> Edit(int? id)
        // {
        //     // if (id == null)
        //     // {
        //     //     return NotFound();
        //     // }

        //     // var tb_stock_in = await _context.Tb_stock_in.FindAsync(id);
        //     // if (tb_stock_in == null)
        //     // {
        //     //     return NotFound();
        //     // }
        //     // return View(tb_stock_in);
        // }

        // POST: StockIn/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("id_in,prd_code,prd_inqty,in_status,in_datetime,in_name,in_last_uptime,in_last_upname")] Tb_stock_in tb_stock_in)
        {
            if (id != tb_stock_in.id_in)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(tb_stock_in);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!Tb_stock_inExists(tb_stock_in.id_in))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(tb_stock_in);
        }

        // GET: StockIn/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tb_stock_in = await _context.Tb_stock_in
                .FirstOrDefaultAsync(m => m.id_in == id);
            if (tb_stock_in == null)
            {
                return NotFound();
            }

            return View(tb_stock_in);
        }

        // POST: StockIn/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var tb_stock_in = await _context.Tb_stock_in.FindAsync(id);
            _context.Tb_stock_in.Remove(tb_stock_in);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool Tb_stock_inExists(int id)
        {
            return _context.Tb_stock_in.Any(e => e.id_in == id);
        }
        private bool IsNotLogin()
        {
            return String.IsNullOrEmpty(HttpContext.Session.GetString("_Name"));
        }
    }
}

Views/StockIn/Create.cshtml
@model PTum.Models.Tb_stock_in
@using Microsoft.Extensions.Configuration
@inject IConfiguration Configuration

@{
    ViewData["Title"] = "Stock in";
}

<div class="row">

<div class="col-6 offset-3">
  <form asp-action="Create">
    <div class="card card-outline card-success">
      <div class="card-header">
          <h3 class="card-title">Add qty</h3>
      </div>
      <div class="card-body">
        <div class="row">
            <div class="col">
              <label class="control-label">Type</label>
            </div>
            <div class="col">
                <div class="form-check">
                    <input class="form-check-input" type="radio" name="radio1" id="type1" checked value="All">
                    <label class="form-check-label" for="type1">All</label>
                </div>
            </div>
            <div class="col">
                <div class="form-check">
                    <input class="form-check-input" type="radio" name="radio1" id="type2" value="Accessories">
                    <label class="form-check-label" for="type2">Accessories</label>
                </div>
            </div>
            <div class="col">
                <div class="form-check">
                    <input class="form-check-input" type="radio" name="radio1" id="type3" value="Desktop">
                    <label class="form-check-label" for="type3">Desktop</label>
                </div>
            </div>
        </div>
          <div asp-validation-summary="ModelOnly" class="text-danger"></div>
          <div class="form-group">
              <label asp-for="prd_code" class="control-label"></label>
              <select asp-for="prd_code" class="form-control">
              </select>
              <span asp-validation-for="prd_code" class="text-danger"></span>
          </div>
          <div class="form-group">
              <label asp-for="prd_inqty" class="control-label"></label>
              <input asp-for="prd_inqty" class="form-control" />
              <span asp-validation-for="prd_inqty" class="text-danger"></span>
          </div>
          <div class="form-group text-right">
            <button type="submit" class="btn btn-success">Submit</button>
            <a class="btn btn-outline-secondary" href='@Url.Action("Index", "StockIn")'>Back</a>
          </div>
      </div>
    </div>
  </form>
</div>

</div>

@section scripts{
<script type="text/babel">

    var type = "All";
    var url = '@Url.Action("All", "Product")'

    $('#prd_code').select2({
      theme: 'bootstrap4',
      placeholder: 'Product code',
      allowClear: true,
      ajax: {
        url: url,
        dataType: 'json',
        processResults: function (data) {
          var option = $.map(data, function (obj) {
            obj.id = obj.prd_code ;
            obj.text = obj.prd_code + " - " + obj.prd_name; 
            return obj;
          });
          return {results: option};
        }                  
      } 
      })

    $('input[name="radio1"]').on('change', function(){
      type = $(this).val()
      url = '@Url.Action("", "Product")'+"/"+type


      if(type=="Desktop"){
        $('#prd_inqty').val("1");
      }
      else{
        $('#prd_inqty').val("");
      }


      $('#prd_code').select2({
      theme: 'bootstrap4',
      placeholder: 'Product code',
      allowClear: true,
      ajax: {
        url: url,
        dataType: 'json',
        processResults: function (data) {
          var option = $.map(data, function (obj) {
            obj.id = obj.prd_code ;
            obj.text = obj.prd_code + " - " + obj.prd_name; 
            return obj;
          });
          return {results: option};
        }                  
      } 
      })

    })


    
@*     $('#prd_code_desktop').select2({
      theme: 'bootstrap4',
      placeholder: 'Product code',
      allowClear: true,
      ajax: {
        url: '@Url.Action("Desktop", "Product")',
        dataType: 'json',
        processResults: function (data) {
          var option = $.map(data, function (obj) {
            obj.id = obj.prd_code ;
            obj.text = obj.prd_code + " - " + obj.prd_name; 
            return obj;
          });
          return {results: option};
        },
        data: function (params) {
          var query = {
            q: params.term,
          }

          // Query parameters will be ?search=[term]&type=public
          return query;
        }      
      } 
    })  *@ 
</script> 
}

Views/StockIn/Delete.cshtml
@model PTum.Models.Tb_stock_in

@{
    ViewData["Title"] = "Delete stock in";
}

<div class="card card-danger">
    <div class="card-header">
        <h3 class="card-title">Are you sure you want to delete this?</h3>
    </div>
    <div class="card-body">
        <dl class="row">
            <dt class = "col-sm-2">
                @Html.DisplayNameFor(model => model.prd_code)
            </dt>
            <dd class = "col-sm-10">
                @Html.DisplayFor(model => model.prd_code)
            </dd>
            <dt class = "col-sm-2">
                @Html.DisplayNameFor(model => model.prd_inqty)
            </dt>
            <dd class = "col-sm-10">
                @Html.DisplayFor(model => model.prd_inqty)
            </dd>
            <dt class = "col-sm-2">
                @Html.DisplayNameFor(model => model.in_status)
            </dt>
            <dd class = "col-sm-10">
                @Html.DisplayFor(model => model.in_status)
            </dd>
            <dt class = "col-sm-2">
                @Html.DisplayNameFor(model => model.in_datetime)
            </dt>
            <dd class = "col-sm-10">
                @Html.DisplayFor(model => model.in_datetime)
            </dd>
            <dt class = "col-sm-2">
                @Html.DisplayNameFor(model => model.in_name)
            </dt>
            <dd class = "col-sm-10">
                @Html.DisplayFor(model => model.in_name)
            </dd>
            <dt class = "col-sm-2">
                @Html.DisplayNameFor(model => model.in_last_uptime)
            </dt>
            <dd class = "col-sm-10">
                @Html.DisplayFor(model => model.in_last_uptime)
            </dd>
            <dt class = "col-sm-2">
                @Html.DisplayNameFor(model => model.in_last_upname)
            </dt>
            <dd class = "col-sm-10">
                @Html.DisplayFor(model => model.in_last_upname)
            </dd>
        </dl>
        
        <form asp-action="Delete" class="text-center">
            <input type="hidden" asp-for="id_in" />
            <input type="submit" value="Delete" class="btn btn-danger" >
        </form>
    </div>
</div>

<div class="text-center">
    <a asp-action="Index"><i class="fas fa-chevron-circle-left"></i> Back to List</a>
</div>

Views/StockIn/Details.cshtml
@model PTum.Models.Tb_stock_in

@{
    ViewData["Title"] = "Details stock in";
}



<div class="card card-info">
    <div class="card-header">
        <h3 class="card-title">Stock in detail</h3>
    </div>
    <div class="card-body">
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.prd_code)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.prd_code)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.prd_inqty)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.prd_inqty)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.in_datetime)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.in_datetime)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.in_name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.in_name)
        </dd>
    </dl>
    </div>
</div>


<div class="text-center">
    <a asp-action="Index"><i class="fas fa-chevron-circle-left"></i> Back to List</a>
</div>

Views/StockIn/Index.cshtml
@model IEnumerable<PTum.Models.Tb_stock_in>
@using Microsoft.Extensions.Configuration
@inject IConfiguration Configuration

@{
    ViewData["Title"] = "Stock in";
}

<style>
.uploader {
  display: block;
  clear: both;
  margin: 0 auto;
  width: 100%;
}
.uploader:hover{
  cursor: pointer;
}
.uploader label {
  float: left;
  clear: both;
  width: 100%;
  padding: 2rem 1.5rem;
  text-align: center;
  background: #fff;
  border-radius: 7px;
  border: 3px dashed #eee;
  -webkit-transition: all .2s ease;
  transition: all .2s ease;
  -webkit-user-select: none;
     -moz-user-select: none;
      -ms-user-select: none;
          user-select: none;
}
.uploader label.success{
    background: #C5E1A5;
}
.uploader label.hover #start i.fas {
  -webkit-transform: scale(0.8);
          transform: scale(0.8);
  opacity: 0.3;
}
.uploader #start {
  float: left;
  clear: both;
  width: 100%;
}
.uploader #start.hidden {
  display: none;
}
.uploader #start i.fas {
  font-size: 50px;
  margin-bottom: 1rem;
  -webkit-transition: all .2s ease-in-out;
  transition: all .2s ease-in-out;
}
.uploader #response {
  float: left;
  clear: both;
  width: 100%;
}
.uploader input[type="file"] {
  display: none;
}
.uploader div {
  margin: 0 0 .5rem 0;
  color: #5f6982;
}
</style>

<div class="card">
    <div class="card-body">
        <div class="row">
            <div class="col-md-3 col-sm-6">
            <!-- Date and time range -->
                <div class="form-group">
                    <label>Date range button:</label>
                    <div class="input-group">
                        <button type="button" class="btn btn-default float-right" id="daterange-btn">
                            <i class="far fa-calendar-alt"></i> Choose range
                            <i class="fas fa-caret-down"></i>
                        </button>
                    </div>
                </div><!-- /.form group --> 
            </div>
        </div>
    </div>
</div>


<div class="card">
    <div class="card-body">
        <table class="table table-sm table-bordered" id="stock-in">
            <thead>
                <tr>
                    <th class="text-center">
                        @Html.DisplayNameFor(model => model.prd_code)
                    </th>
                    <th class="text-center">
                        @Html.DisplayNameFor(model => model.prd_inqty)
                    </th>
                    <th class="text-center">
                        @Html.DisplayNameFor(model => model.in_datetime)
                    </th>
                    <th class="text-center">
                        @Html.DisplayNameFor(model => model.in_name)
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
        @foreach (var item in Model) {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.prd_code)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.prd_inqty)
                    </td>
                    <td>
                        @* @Html.DisplayFor(modelItem => item.in_datetime)  *@
                        @Convert.ToDateTime(item.in_datetime).ToString("yyyy-MM-dd HH:mm:ss")
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.in_name)
                    </td>
                    <td class="text-center text-sm">
                        <a asp-action="Details" asp-route-id="@item.id_in" class="text-info"><i class="far fa-eye"></i> Details</a>
                        @* <a asp-action="Edit" asp-route-id="@item.id_in" class="text-primary"><i class="fas fa-pen"></i> Edit</a> *@
                        <a asp-action="Delete" asp-route-id="@item.id_in" class="text-danger"><i class="far fa-trash-alt"></i> Delete</a>
                    </td>
                </tr>
        }
            </tbody>
        </table>
    </div>
</div>


<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Import stock</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <form asp-action="create" method="post" enctype="multipart/form-data" id="form-upload" >
      <div class="modal-body">
            <div id="file-upload-form" class="uploader">
                <input id="file-upload" type="file" name="files" accept=".xls,.xlsx" />
                <label for="file-upload">
                    <div id="start">
                        <i class="fas fa-cloud-upload-alt"></i>
                        <div class="noti">Drop files here or click to upload..</div>
                    </div>
                </label>
            </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-success" disabled>Upload</button>
      </div>
      </form>
    </div>
  </div>
</div>

@section scripts{
<script type="text/babel">
   

    var table = $("#stock-in").DataTable({
        "responsive": true, 
        "lengthChange": false, 
        "lengthMenu": [[10, 25, 50, -1], [10, 25, 50, "All"]], 
        "autoWidth": false,
        "order": [[ 2, "desc" ]],
        "buttons": [
            {
                extend: "pageLength",
                className: "btn-sm",
            },
            {
                text: '<i class="fas fa-plus"></i> New',
                action: function ( e, dt, node, config ) {
                    location.href="@Url.Action("Create", "StockIn")"
                },
                className: "btn-sm btn-outline-success",
                init: function(api, node, config) {
                    $(node).removeClass('btn-secondary')
                }
            },
            {
                text: '<i class="fas fa-plus"></i> Import',
                action: function ( e, dt, node, config ) {
                    $('#myModal').modal('show')
                },
                className: "btn-sm btn-outline-success",
                init: function(api, node, config) {
                    $(node).removeClass('btn-secondary')
                }
            },
            {
                text: '<i class="fas fa-file-download"></i> Download template',
                action: function ( e, dt, node, config ) {
                    location.href='@Url.Action("Excel","StockIn")'
                },
                className: "btn-sm btn-outline-secondary",
                init: function(api, node, config) {
                    $(node).removeClass('btn-secondary')
                }
            },
            {
                extend: "excel",
                text: '<i class="far fa-file-excel"></i> Export excel',
                className: "btn-sm btn-outline-secondary",
                init: function(api, node, config) {
                    $(node).removeClass('btn-secondary')
                }
            },
        ]
    })
    
    table.buttons().container().appendTo('#stock-in_wrapper .col-md-6:eq(0)')

    var minDate = new Date("@Configuration["MyProject:date_start_project"]");
    var maxDate = new Date()

    var datepickers = [{
        id: 'startdate',
        coid: 'enddate',
        value: new Date(minDate).toISOString(),
        limiter: 'minDate'
    }, 
    {
        id: 'enddate',
        coid: 'startdate',
        value: new Date(maxDate).toISOString(),
        limiter: 'maxDate'
    }];



    $('#reservation').daterangepicker({
            opens: 'left',
            "startDate": minDate,
            "endDate": maxDate,
            locale: {
                format: 'YYYY-MM-DD' 
            },
        }, 
        function(start, end, label) {
            console.log("A new date selection was made: " + start.format('YYYY-MM-DD') + ' to ' + end.format('YYYY-MM-DD'));
            datepickers[0].value = new Date(start).toISOString(); 
            datepickers[1].value = new Date(end).toISOString(); 
            table.draw();
        }
    )

    //External search function
    $.fn.DataTable.ext.search.push((settings, row) => {
        var rawDate = moment(row[2]).format("YYYY-MM-DDTHH:mm:ss");
        var rowDate = new Date(rawDate).toISOString();
        @* rowDate = new Date(row[2]).toISOString(); *@
        return (rowDate >= datepickers[0].value || datepickers[0].value == null) && (rowDate <= datepickers[1].value || datepickers[1].value == null);
    });

    //Date range as a button
    $('#daterange-btn').daterangepicker(
      {
        ranges   : {
          'Today'       : [moment(), moment()],
          'Yesterday'   : [moment().subtract(1, 'days'), moment().subtract(1, 'days')],
          'Last 7 Days' : [moment().subtract(6, 'days'), moment()],
          'Last 30 Days': [moment().subtract(29, 'days'), moment()],
          'This Month'  : [moment().startOf('month'), moment().endOf('month')],
          'Last Month'  : [moment().subtract(1, 'month').startOf('month'), moment().subtract(1, 'month').endOf('month')]
        },
        startDate: moment().subtract(29, 'days'),
        endDate  : moment()
      },
      function (start, end) {
            console.log(start.format('MMMM D, YYYY') + ' - ' + end.format('MMMM D, YYYY'))
            datepickers[0].value = new Date(start).toISOString(); 
            datepickers[1].value = new Date(end).toISOString(); 
            table.draw();
      }
    )  

    $('#file-upload').change(function(){
        if( $(this).val() !=""){
            var fileName = $(this).val().replace(/^.*[\\\/]/, '');
            var ext = fileName.split('.').pop();
            if(ext=="xlsx" || ext=="xls"){
                $(this).closest('.uploader').find('label').addClass('success')
                $(this).closest('.uploader').find('label .noti').text(fileName)
                $(':input[type="submit"]').prop('disabled', false);
            }  
            else{
                $(this).empty()
                $(this).closest('.uploader').find('label').removeClass('success')
                $(this).closest('.uploader').find('label .noti').text("Drop files here or click to upload..")
                $(':input[type="submit"]').prop('disabled', true);
            }
        }
        else{
            $(':input[type="submit"]').prop('disabled', true);
            $('#form-upload').addEventListener('submit', event => {
                event.preventDefault();
            });
        }
    })


  $("#form-upload").submit(function(e){
    e.preventDefault();
      var formData = new FormData(this);
      console.log(formData)
      $.ajax({
        type: "POST",
        url: '@Url.Action("CreateExcel", "StockIn")',
        dataType: "json",
        async: false,
        cache: false,
        processData: false,
        contentType: false,
        headers: { 
          "RequestVerificationToken": $('input[name="__RequestVerificationToken"]').val(),
        },
        data: formData,
        error: function (result) {
          Toast.fire({
            icon: 'error',
            title: 'Please contact developer'
        })
      },
      success: function (result) {
        console.log(result);
        if (result.success) {
          Toast.fire({
            icon: 'success',
            title: 'Successfully upload file'
          })
          setTimeout(function(){ location.reload() }, 1500);
        }
        else {
          Toast.fire({
            icon: 'error',
            title: 'Please contact developer'
          })
        }
      }
    });
  });

</script>
}